let dizionario = {
 "ciao": "uè",
  "come stai": "come staje",
  "sto bene": "stong' bbuon",
  "tutto bene": "tutt'apposto",
  "che fai": "che staie facenno",
  "dove vai": "addò vaie",
  "non lo so": "nun 'o ssaccio",
  "grazie": "grazie",
  "prego": "prego",
  "scusa": "scusame",
  "buongiorno": "buongiorno",
  "buonasera": "buonasera",
  "quanto costa": "quanto costa",
  "ho fame": "tengo fame",
  "ho sete": "tengo sete",
  "sono stanco": "sto stanco",
  "vieni qui": "vieni ccà",
  "andiamo": "jamm",
  "non capisco": "nun capisco",
  "è bello": "è bbello",
  "è brutto": "è bbrutto",
  "che succede": "che succede",
  "tutto ok": "tutto bbuon",
  "va bene": "va bbuon"
 };
